#! /bin/sh

# loop over $@; store last arg in $remote
for remote; do :; done
if [ $# -eq 0 ]; then
	echo "Usage: $0 [filename] command(s)"
	echo
	echo "Examples:"
	echo "\t$0 pull origin"
	echo "\t$0 fetch upstream"
	echo "\t$0 remote -v"
elif [ -f $remote ]; then
	grep -v '^#' $remote | while read dir
	do
		[ -z "$dir" ] && continue
		cd $dir
		if [ $? -eq 0 ]; then
			echo
			pwd
			git $*
			cd ..
		fi
	done
else
	find -maxdepth 1 -type d -exec sh -c "cd '{}' && echo && pwd && git $*" \;
fi

