#!/bin/sh
#
# pg_dumpbackup: Shortcut for pg_dump backups using database urls
# IPv6 urls are not supported

dburl=${1:-$DATABASE_URL}
if [ "$1" = '-h' ] || [ "$1" = '--help' ] || [ -z "$dburl" ]; then
	 echo "Usage: pg_dumpbackup postgres://username[:password]@host:port/database[|\$DATABASE_URL] [BACKUP FILENAME]"
     echo "Shortcut for pg_dump backups using database urls"
	 exit
fi

cnxn=${dburl%/*}
cnxn=${cnxn##*/}
db=${dburl##*/}
if [ "$cnxn" != "${cnxn#*\@}" ]; then
	userpass=${cnxn%\@*}
	hostport=${cnxn#*\@}
else
	userpass=postgres
	hostport=$cnxn
fi
user=${userpass%%\:*}
if [ "$hostport" != "${hostport#*\:}" ]; then
	host=${hostport%\:*}
	port=${hostport##*\:}
else
	host=$hostport
	port=5432
fi
backup=${2:-${db}-${host}}
echo "Backup postgres://${user}@${host}:${port}/${db}"
pg_dump -cCO -d $db -h $host -p $port -U $user | gzip -c - > "${backup}-$(date '+%Y%m%d-%H%M%S').sql.gz"
