#!/bin/sh
#
# Install: ln -s ~/bin/s-i <IP|FQDN>
# Usage: ./<IP|FQDN> cmd pemfile user

ip=`basename $0`
cmd=${1:-ssh}
pemfile=$2
if [ ! -f "$pemfile" ]; then
	user=$pemfile
	pemfile=`echo $ip | cut -d . -f 2`.pem
else
	user=$3
fi
user=${user:-ubuntu}

$cmd -i $pemfile $user@$ip
